HAT_ASSET_TYPE = 8
HEAD_ASSET_TYPE = 17
FACE_ASSET_TYPE = 18
GEAR_ASSET_TYPE = 19
TORSO_ASSET_TYPE = 27
RIGHT_ARM_ASSET_TYPE = 28
LEFT_ARM_ASSET_TYPE = 29
RIGHT_LEG_ASSET_TYPE = 31
LEFT_LEG_ASSET_TYPE = 30
HAIR_ACCESSORY = 41
FACE_ACCESSORY = 42
NECK_ACCESSORY = 43
SHOULDER_ACCESSORY = 44
BACK_ACCESSORY = 46
WAIST_ACCESSORY = 47


class SUBCATEGORY:
    """
    USED FOR CATALOG v1/v2 SEARCHES
    """

    ALL = 1
    COLLECTIBLES = 2
    CLOTHING = 3
    BODYPARTS = 4
    GEAR = 5
    HATS = 9
    FACES = 10
    SHIRTS = 12
    TSHIRTS = 13
    PANTS = 14
    HEADS = 15
    ACCESSORIES = 19
    HAIRACCESSORIES = 20
    FACEACCESSORIES = 21
    NECKACCESSORIES = 22
    SHOULDERACCESSORIES = 23
    FRONTACCESSORIES = 24
    BACKACCESSORIES = 25
    WAISTACCESSORIES = 26
    AVATARANIMATIONS = 27
    BUNDLES = 37
    ANIMATIONBUNDLES = 38
    EMOTEANIMATIONS = 39
    COMMUNITYCREATIONS = 40
    MELEE = 41
    RANGED = 42
    EXPLOSIVE = 43
    POWERUP = 44
    NAVIGATION = 45
    MUSICAL = 46
    SOCIAL = 47
    BUILDING = 48
    TRANSPORT = 49
